
version: "3.7"
services:
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: always
        command: -H unix:///var/run/docker.sock
        ports:
          - "9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ${USER_DIR}/portainer/data:/data
          - "/etc/localtime:/etc/localtime:ro"
          - ${USER_DIR}/portainer/shared:/shared
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}

    watchtower:
        container_name: watchtower
        restart: always
        image: v2tec/watchtower:armhf-latest
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        command: --schedule "0 0 3 * * *" --cleanup

    qbittorrent-vpn:
        container_name: qbittorrent-vpn
        image: trigus42/qbittorrentvpn
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}
          - VPN_ENABLED=yes
          - VPN_TYPE=openvpn
          - LAN_NETWORK=10.0.0.0/24
          - VPN_USERNAME=${PIA_USERNAME}
          - VPN_PASSWORD=${PIA_PASSWORD}
        volumes:
          - ${USER_DIR}/qbittorrent-vpn:/config
          - ${DOWNLOAD_DIR}:/downloads
        ports:
          - 80:8080
          - 443:8080
        restart: unless-stopped
        cap_add:
          - NET_ADMIN
          - SYS_MODULE
        sysctls:
          - net.ipv4.conf.all.src_valid_mark=1

    plex:
        image: lscr.io/linuxserver/plex:arm32v7-latest
        container_name: plex
        network_mode: host
        environment:
          - TZ=${TZ}
          - PUID=${PUID}
          - PGID=${PGID}
          - VERSION=docker
        volumes:
          - ${USER_DIR}/plex:/config
          - ${MOVIE_DIR}:/movies
          - ${TV_DIR}:/tv
        restart: unless-stopped

    prowlarr:
        image: lscr.io/linuxserver/prowlarr:develop
        container_name: prowlarr
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}
        volumes:
          - ${USER_DIR}/prowlarr:/config
        ports:
          - 9696:9696
        restart: unless-stopped

    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}
        volumes:
          - ${USER_DIR}/sonarr:/config
          - ${TV_DIR}:/tv
          - ${DOWNLOAD_DIR}:/data
        ports:
          - 8989:8989
        restart: unless-stopped

    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}
        volumes:
          - ${USER_DIR}/radarr:/config
          - ${MOVIE_DIR}:/movies
          - ${DOWNLOAD_DIR}:/data
        ports:
          - 7878:7878
        restart: unless-stopped
        
    bazarr:
      image: lscr.io/linuxserver/bazarr:latest
      container_name: bazarr
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
      volumes:
        - ${USER_DIR}/bazarr:/config
        - ${MOVIE_DIR}:/movies
        - ${TV_DIR}:/tv
      ports:
        - 6767:6767
      restart: unless-stopped
